name: Python Package using Conda

on: 
  pull_request:
    branches: [master]
    types: [synchronize, opened, reopened, ready_for_review]

jobs:
  build-and-test:
    name: Test on (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
    steps:
      - uses: actions/checkout@v2
      - uses: s-weigand/setup-conda@v1
        with:
          python-version: 3.8
      - name: Which conda/python
        run: |
          conda --version
          python --version
      - name: Install dependencies
        run: |
          conda install mpi mpi4py
          pip install neuron
          pip install LFPy
          pip install .
          pip install pytest
      - name: pip list
        run: |
          pip list
      - name: Test with pytest and build coverage report
        run: |
          pytest -s
